[package]
name = "math"
version = "0.1.0"
authors = ["sander.bockstaele <sander.bockstaele@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.9.0" }
epi = { version = "0.9.0" }
eframe = "0.9.0"
emath = "0.9.0"
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1", features = ["derive"], optional = true }